# POST Order
POST {{server}}/api/orders
Content-Type: application/json

// CreateOrderCommand
{
   "OrderId" : 1,
   "CustomerId" : 1,
   "Products" : [
     {
       "ProductId" : 1,
       "Quantity" : 5
     },
     {
      "ProductId" : 2,
      "Quantity" : 5
     }
   ]
}
